rework exit code redirection

diff --git a/.github/workflows/run_min_dep_tests.yml b/.github/workflows/run_min_dep_tests.yml
--- a/.github/workflows/run_min_dep_tests.yml
+++ b/.github/workflows/run_min_dep_tests.yml
@@ -79,15 +79,16 @@ jobs:
         shell: bash -l {0}
         run: |
           export PATH="$pythonLocation:$PATH"
-          python -m pytest -s --cov dascore --cov-append --cov-report=xml
+          EXIT_CODE=0
+          python -m pytest -s --cov dascore --cov-append --cov-report=xml || EXIT_CODE = $?
           # Check the exit code is related to sporadic failures on mac, see #312
           if [ $EXIT_CODE -eq 132 ]; then
             gh run cancel ${{ github.run_id }}
             gh run watch ${{ github.run_id }}
+          # also make sure proper exit code is returned if not 132 or 0
           elif [ $EXIT_CODE -ne 0 ]; then
             exit $EXIT_CODE
           fi
-
       # Runs examples in docstrings
       - name: test docstrings
         shell: bash -l {0}
