Upath support and basic config

diff --git a/.github/workflows/run_min_dep_tests.yml b/.github/workflows/run_min_dep_tests.yml
--- a/.github/workflows/run_min_dep_tests.yml
+++ b/.github/workflows/run_min_dep_tests.yml
@@ -32,6 +32,7 @@ jobs:
     outputs:
       # Shared values live in .github/actions/load-shared-vars/action.yml
       python-matrix: ${{ steps.load-vars.outputs.python-min-deps-matrix }}
+      os-matrix: ${{ steps.load-vars.outputs.test-os-matrix }}
     steps:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/load-shared-vars
@@ -39,16 +40,21 @@ jobs:
 
   test_code_min_deps:
     needs: setup
-    timeout-minutes: 25
+    timeout-minutes: 35
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ ubuntu-latest, macos-latest, windows-latest ]
+        # Defined in .github/actions/load-shared-vars/action.yml
+        os: ${{ fromJson(needs.setup.outputs.os-matrix) }}
         # Defined in .github/actions/load-shared-vars/action.yml
         python-version: ${{ fromJson(needs.setup.outputs.python-matrix) }}
 
     # only run if CI isn't turned off
     if: github.event_name == 'push' || !contains(github.event.pull_request.labels.*.name, 'no_ci')
+
+    env:
+      # Determine if this should drop into a debugger if any tests fail.
+      debug_enabled: ${{ github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'debug') }}
 
     steps:
       - uses: actions/checkout@v4
@@ -66,10 +72,28 @@ jobs:
 
       # Runs test suite and calculates coverage
       - name: run test suite
+        id: run_test_suite
+        continue-on-error: ${{ env.debug_enabled == 'true' }}
         shell: bash -el {0}
         run: ./.github/test_code.sh
 
       # Runs examples in docstrings
       - name: test docstrings
+        id: run_docstrings
+        continue-on-error: ${{ env.debug_enabled == 'true' }}
         shell: bash -el {0}
         run: ./.github/test_code.sh doctest
+
+      # Debug access is limited to the workflow actor's GitHub SSH keys.
+      # Connect from a machine that has the matching private key loaded.
+      - name: Setup tmate session
+        if: env.debug_enabled == 'true' && (steps.run_test_suite.outcome == 'failure' || steps.run_docstrings.outcome == 'failure')
+        uses: mxschmitt/action-tmate@v3
+        timeout-minutes: 30
+        with:
+          limit-access-to-actor: true
+
+      - name: fail job after debug session if tests failed
+        if: steps.run_test_suite.outcome == 'failure' || steps.run_docstrings.outcome == 'failure'
+        shell: bash -el {0}
+        run: exit 1
